guacd:
  hostname: guacd
  image: danielguerra/guacamole-guacd
guadb:
  hostname: guadb
  image: danielguerra/guacamole-db
guaweb:
  image: danielguerra/guacamole-webserver
  links:
    - guacd
    - "guadb:db"
  ports:
    - "8080"
