guacd:
  hostname: guacd
  image: danielguerra/guacamole-guacd
guadb:
  hostname: guadb
  image: danielguerra/guacamole-db
  environment:
    - MYSQL_ROOT_PASSWORD=mypass
guaweb:
  image: danielguerra/guacamole-webserver
  links:
    - guacd
    - "guadb:db"
  ports:
    - "8080"
